# Generated by Django 6.1 on 2026-08-14 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.assignment'),
        ),
    ]
