# Generated by Django 6.1 on 2026-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_grade_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_submissions/'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
