# Generated by Django 6.1 on 2026-08-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_communitynotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('translation', models.CharField(max_length=200)),
                ('pronunciation', models.CharField(blank=True, max_length=200)),
                ('definition', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('synonyms', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, default='B1', max_length=2)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('word',),
            },
        ),
    ]
