# Generated by Django 6.1 on 2026-08-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_vocabulary_created_by_vocabulary_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='definition',
            field=models.TextField(),
        ),
    ]
