# Generated by Django 6.1 on 2026-08-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_readingpassage_readingquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TFNG', 'True / False / Not Given'), ('YNNG', 'Yes / No / Not Given'), ('SHORT', 'Short Answer'), ('SENTENCE', 'Sentence Completion'), ('SUMMARY', 'Summary Completion'), ('NOTE', 'Note Completion'), ('TABLE', 'Table Completion'), ('HEADINGS', 'Matching Headings'), ('INFORMATION', 'Matching Information'), ('FEATURES', 'Matching Features')], default='MCQ', max_length=20),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='correct_answer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
